/**
 * The audit log, and the decision cache.
 *
 * Two things that sit either side of `can()`: one remembers what it decided,
 * the other avoids asking twice.
 */

import type {
  Action,
  Decision,
  Grant,
  Principal,
  Resource,
  Timestamp,
} from "./index.js";
import { can, explain } from "./index.js";

/** The two methods an audit row needs from a database. Mirrors `GrantDatabase`. */
export interface AuditDatabase {
  execute(sql: string, params: unknown[]): Promise<{ rowsAffected: number }>;
  query(
    sql: string,
    params: unknown[],
  ): Promise<Array<{ get(c: string): unknown }>>;
}

/** One recorded decision, as it comes back out of the log. */
export interface AuditEntry {
  decidedAt: string;
  principal: Principal;
  action: Action;
  resource: Resource;
  allowed: boolean;
  reason: Decision["reason"];
}

const resourceId = (r: Resource): string => (r.kind === "platform" ? "" : r.id);
const principalId = (p: Principal): string =>
  p.kind === "anonymous" ? "" : p.id;

/**
 * Append-only storage for authorization decisions.
 *
 * The table is generated by `fid derive` as `migrations/0002_audit.sql` when
 * `[identity] audit = true`, so its `CHECK` on `reason` lists exactly the
 * `Reason` variants the rule can return. A reason the rule produces and the
 * table cannot store fails loudly rather than losing why.
 *
 * **Append-only by discipline, not by trigger.** SQLite and Postgres disagree
 * about how to forbid an UPDATE, and a log whose immutability is enforced
 * differently on each vendor is one whose guarantee nobody can state. This
 * class offers no update and no delete; enforcing that against a determined
 * writer is the database role's job, not a method's.
 */
export class AuditLog {
  private readonly table: string;
  private readonly dialect: "sqlite" | "postgres";

  constructor(
    private readonly db: AuditDatabase,
    options: { table?: string; dialect?: "sqlite" | "postgres" } = {},
  ) {
    const table = options.table ?? "grants_audit";
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(table)) {
      throw new Error(`AuditLog: invalid table name ${JSON.stringify(table)}`);
    }
    this.table = table;
    this.dialect = options.dialect ?? "sqlite";
  }

  /** `?` becomes `$1, $2, ...` for Postgres, which does not accept `?`. */
  private sql(query: string): string {
    if (this.dialect !== "postgres") return query;
    let n = 0;
    return query.replace(/\?/g, () => `$${++n}`);
  }

  private static readonly COLUMNS = `decided_at, principal_kind, principal_id, action,
                resource_kind, resource_id, allowed, reason`;

  /** Record one decision. */
  async record(
    principal: Principal,
    action: Action,
    resource: Resource,
    decision: Decision,
    at: Date = new Date(),
  ): Promise<void> {
    await this.db.execute(
      this.sql(
        `INSERT INTO ${this.table}
           (${AuditLog.COLUMNS})
         VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
      ),
      [
        at.toISOString(),
        principal.kind,
        principalId(principal),
        action,
        resource.kind,
        resourceId(resource),
        // Not a boolean: SQLite has none, and passing `true` through a driver
        // that stringifies it writes "true" into an INTEGER column.
        decision.allowed ? 1 : 0,
        decision.reason,
      ],
    );
  }

  /**
   * Decide and record, in one call.
   *
   * The reason exists only at the moment of decision — reconstructing it
   * afterwards from the grants table is guesswork, because the table has moved
   * on by the time anyone reads the log. Which is why this wraps `explain` and
   * not `can`.
   */
  async decide(
    principal: Principal,
    action: Action,
    resource: Resource,
    grants: readonly Grant[],
    now: Timestamp | null = null,
  ): Promise<Decision> {
    const decision = explain(principal, action, resource, grants, now);
    await this.record(principal, action, resource, decision);
    return decision;
  }

  /** What happened to this principal, most recent first. */
  async forPrincipal(principal: Principal, limit = 100): Promise<AuditEntry[]> {
    const rows = await this.db.query(
      this.sql(
        `SELECT ${AuditLog.COLUMNS}
           FROM ${this.table}
          WHERE principal_kind = ? AND principal_id = ?
          ORDER BY decided_at DESC
          LIMIT ${Number(limit) | 0}`,
      ),
      [principal.kind, principalId(principal)],
    );
    return rows.map(toEntry);
  }

  /** Who was refused, most recent first — the query an incident starts with. */
  async denials(limit = 100): Promise<AuditEntry[]> {
    const rows = await this.db.query(
      this.sql(
        `SELECT ${AuditLog.COLUMNS}
           FROM ${this.table}
          WHERE allowed = ?
          ORDER BY decided_at DESC
          LIMIT ${Number(limit) | 0}`,
      ),
      [0],
    );
    return rows.map(toEntry);
  }
}

function toEntry(row: { get(c: string): unknown }): AuditEntry {
  const kind = String(row.get("principal_kind"));
  const rKind = String(row.get("resource_kind"));
  const allowed = row.get("allowed");
  return {
    decidedAt: String(row.get("decided_at")),
    principal:
      kind === "anonymous"
        ? { kind: "anonymous" }
        : ({ kind, id: String(row.get("principal_id")) } as Principal),
    action: String(row.get("action")) as Action,
    resource:
      rKind === "platform"
        ? { kind: "platform" }
        : ({ kind: rKind, id: String(row.get("resource_id")) } as Resource),
    // SQLite gives back 0/1, Postgres gives back a boolean. Both must read as
    // the same thing or an audit is wrong in the direction that matters.
    allowed: allowed === true || allowed === 1 || allowed === "1",
    reason: String(row.get("reason")) as Decision["reason"],
  };
}

// -- Caching -----------------------------------------------------------------

/** Separator for cache keys: a unit separator cannot occur in an id or kind. */
const SEP = String.fromCharCode(31);

/**
 * A bounded cache of recent verdicts.
 *
 * `can()` is O(grants), and a Worker answering it per request against a table
 * fetched per request is the shape that makes authorization the slow part of a
 * page. This caches the verdict, not the grants.
 *
 * **It holds no clock and expires nothing by time.** A cache that decided when
 * its own contents were stale would be a second, quieter copy of the expiry
 * rule, and the two would disagree — the cache would be the one that kept
 * saying yes. Call `invalidate()` when the grant table changes. `now` is part
 * of the key, so a different instant is a different question rather than a
 * stale hit.
 */
export class DecisionCache {
  private entries = new Map<string, boolean>();

  constructor(private readonly max = 512) {}

  private static key(
    principal: Principal,
    action: Action,
    resource: Resource,
    now: Timestamp | null,
  ): string {
    return [
      principal.kind,
      principalId(principal),
      action,
      resource.kind,
      resourceId(resource),
      now ?? "noclock",
    ].join(SEP);
  }

  /** Drop every cached verdict. Call when the grant table changes. */
  invalidate(): void {
    this.entries.clear();
  }

  get size(): number {
    return this.entries.size;
  }

  /** Answer from cache, or evaluate and remember. */
  can(
    principal: Principal,
    action: Action,
    resource: Resource,
    grants: readonly Grant[],
    now: Timestamp | null = null,
  ): boolean {
    const key = DecisionCache.key(principal, action, resource, now);
    const hit = this.entries.get(key);
    if (hit !== undefined) return hit;

    const verdict = can(principal, action, resource, grants, now);
    // Insertion-ordered eviction: `Map` iterates in insertion order, so the
    // first key is the oldest. LRU needs bookkeeping proportional to the cache,
    // and at this size it does not pay for the code that has to be right.
    if (this.entries.size >= this.max) {
      const oldest = this.entries.keys().next();
      if (!oldest.done) this.entries.delete(oldest.value);
    }
    this.entries.set(key, verdict);
    return verdict;
  }
}
