[workspace]
resolver = "2"
members = [
    "crates/fiducial",
    "crates/fiducial-core",
    "crates/fiducial-quantity",
    "crates/fiducial-model",
    "crates/fiducial-protocol",
    "crates/fiducial-tauri",
    "crates/fiducial-wasm",
    "crates/fiducial-cli",
]
exclude = ["firmware/*"]

[workspace.package]
version      = "0.1.0"
edition      = "2021"
license      = "MIT"
repository   = "https://github.com/AleksaZCodes/fiducial"
homepage     = "https://github.com/AleksaZCodes/fiducial"
authors      = ["Aleksa Zdravkovic"]
rust-version = "1.82"
