//! Commit messages conform to Conventional Commits.
//!
//! Every other rule in this repository is held up by a test. Commit format was
//! held up by habit — a noticeable asymmetry in a codebase whose whole argument
//! is that care is the wrong mechanism.
//!
//! This closes it without adding a Node toolchain (`commitlint`) for one string
//! check. It runs inside `cargo test`, which CI already executes.
//!
//! # What is checked, and what deliberately is not
//!
//! Only commits **on this branch and not on `main`** — the ones the author can
//! still amend. History is not rewritten to satisfy a rule added later, and a
//! merge commit is not the author's to format.

use std::process::Command;

/// Types permitted by the convention, plus the ones this repository uses.
const TYPES: &[&str] = &[
    "feat", "fix", "docs", "refactor", "chore", "test", "perf", "build", "ci", "style", "revert",
];

/// Subjects that are generated by tooling rather than written by a person.
fn is_tool_generated(subject: &str) -> bool {
    subject.starts_with("Merge ")
        || subject.starts_with("Revert ")
        || subject.starts_with("chore: version packages")
}

/// Split `feat(cli)!: subject` into its parts.
fn parse(subject: &str) -> Result<(&str, Option<&str>, bool, &str), String> {
    let (head, rest) = subject
        .split_once(": ")
        .ok_or_else(|| "missing `: ` — expected `type(scope): subject`".to_string())?;

    let breaking = head.ends_with('!');
    let head = head.strip_suffix('!').unwrap_or(head);

    let (kind, scope) = match head.split_once('(') {
        Some((kind, scope)) => {
            let scope = scope
                .strip_suffix(')')
                .ok_or_else(|| "scope is missing its closing `)`".to_string())?;
            if scope.is_empty() {
                return Err("scope is empty — write `type:` rather than `type():`".into());
            }
            (kind, Some(scope))
        }
        None => (head, None),
    };

    if !TYPES.contains(&kind) {
        return Err(format!(
            "`{kind}` is not a known type. Use one of: {}",
            TYPES.join(", ")
        ));
    }
    if rest.trim().is_empty() {
        return Err("subject is empty".into());
    }
    Ok((kind, scope, breaking, rest))
}

/// The ref to compare against: `origin/main` if it is there, else `main`.
///
/// `origin/main` first, because the **local** `main` is whatever the working
/// copy last checked out and is routinely behind. Resolving it there swept in
/// commits that were already merged upstream — this gate's first run failed on
/// the squash-merge commit of the pull request that introduced it, whose
/// subject GitHub took from the PR title and which nobody can amend. That is
/// the exact case the doc comment above promises to exclude.
fn base_ref() -> Option<&'static str> {
    for candidate in ["origin/main", "main"] {
        let found = Command::new("git")
            .args(["rev-parse", "--verify", "--quiet", candidate])
            .output()
            .ok()?;
        if found.status.success() {
            return Some(candidate);
        }
    }
    // Neither exists — a shallow CI checkout or a fresh clone.
    None
}

/// Commits on this branch that are not on `main`.
fn commits_under_review() -> Option<Vec<(String, String)>> {
    let base = base_ref()?;

    let log = Command::new("git")
        .args([
            "log",
            "--no-merges",
            "--format=%H%x1f%s",
            &format!("{base}..HEAD"),
        ])
        .output()
        .ok()?;
    if !log.status.success() {
        return None;
    }

    Some(
        String::from_utf8_lossy(&log.stdout)
            .lines()
            .filter_map(|line| {
                let (hash, subject) = line.split_once('\u{1f}')?;
                Some((hash.to_string(), subject.to_string()))
            })
            .collect(),
    )
}

#[test]
fn commit_subjects_follow_conventional_commits() {
    let Some(commits) = commits_under_review() else {
        // No `main` to compare against — nothing to check, and failing here
        // would break a fresh clone for a reason unrelated to the change.
        return;
    };

    let mut problems: Vec<String> = Vec::new();

    for (hash, subject) in &commits {
        if is_tool_generated(subject) {
            continue;
        }
        if let Err(reason) = parse(subject) {
            problems.push(format!("  {}  {subject}\n      → {reason}", &hash[..8]));
        }
    }

    assert!(
        problems.is_empty(),
        "commit subjects must follow Conventional Commits \
         (`type(scope): subject`, `!` for breaking):\n\n{}\n\n\
         Amend with `git rebase -i main`, or `git commit --amend` for the tip.\n",
        problems.join("\n")
    );
}

/// A subject line stays readable in `git log --oneline` and as a PR title.
#[test]
fn commit_subjects_are_not_overlong() {
    let Some(commits) = commits_under_review() else {
        return;
    };

    // Conventional Commits suggests 50; 72 is where `git log` starts wrapping in
    // a standard terminal. Enforced at the looser bound — this is about
    // readability, not obedience.
    const MAX: usize = 72;

    let overlong: Vec<String> = commits
        .iter()
        .filter(|(_, subject)| !is_tool_generated(subject))
        .filter(|(_, subject)| subject.chars().count() > MAX)
        .map(|(hash, subject)| {
            format!(
                "  {}  {} chars: {subject}",
                &hash[..8],
                subject.chars().count()
            )
        })
        .collect();

    assert!(
        overlong.is_empty(),
        "commit subjects stay within {MAX} characters so they survive \
         `git log --oneline` and PR titles. Put the detail in the body:\n\n{}\n",
        overlong.join("\n")
    );
}

#[cfg(test)]
mod tests {
    use super::parse;

    #[test]
    fn accepts_the_forms_this_repository_uses() {
        assert!(parse("feat(cli): add a thing").is_ok());
        assert!(parse("docs: explain a thing").is_ok());
        assert!(parse("feat(protocol)!: change the wire").is_ok());
        assert!(parse("fix(i18n): stop the fallback being silent").is_ok());
    }

    #[test]
    fn reports_what_to_fix_rather_than_just_failing() {
        assert!(parse("added a thing").unwrap_err().contains("type(scope)"));
        assert!(parse("nope: a thing")
            .unwrap_err()
            .contains("not a known type"));
        assert!(parse("feat(: a thing").unwrap_err().contains("closing"));
        assert!(parse("feat(): a thing").unwrap_err().contains("empty"));
        assert!(parse("feat: ").unwrap_err().contains("empty"));
    }

    #[test]
    fn breaking_marker_is_recognised_with_and_without_a_scope() {
        assert!(parse("feat!: x").unwrap().2);
        assert!(parse("feat(cli)!: x").unwrap().2);
        assert!(!parse("feat(cli): x").unwrap().2);
    }
}

// ── CLA sign-off ─────────────────────────────────────────────────────────────

/// Commits under review, with author identity and full message.
///
/// A second walk rather than widening `commits_under_review`: that one feeds
/// two subject-shape tests that have no use for a body, and the sign-off check
/// is the only caller that needs one.
fn commits_with_authors() -> Option<Vec<(String, String, String, String)>> {
    let base = base_ref()?;

    // `%x1e` between records, `%x1f` between fields: a commit body contains
    // newlines, so a line-oriented parse would split one commit into many.
    let log = Command::new("git")
        .args([
            "log",
            "--no-merges",
            "--format=%H%x1f%an%x1f%ae%x1f%B%x1e",
            &format!("{base}..HEAD"),
        ])
        .output()
        .ok()?;
    if !log.status.success() {
        return None;
    }

    Some(
        String::from_utf8_lossy(&log.stdout)
            .split('\u{1e}')
            .filter(|record| !record.trim().is_empty())
            .filter_map(|record| {
                let mut parts = record.trim_start().splitn(4, '\u{1f}');
                Some((
                    parts.next()?.to_string(),
                    parts.next()?.to_string(),
                    parts.next()?.to_string(),
                    parts.next()?.to_string(),
                ))
            })
            .collect(),
    )
}

/// Identities that do not need a sign-off, from the file that declares them.
fn cla_exempt() -> Vec<String> {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../.github/cla-exempt.txt");
    let Ok(text) = std::fs::read_to_string(path) else {
        return Vec::new();
    };
    text.lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .map(str::to_string)
        .collect()
}

/// Every outside contribution carries the CLA sign-off trailer.
///
/// `IP-POLICY.md` rule 3: *"No external contribution is merged before a CLA is
/// in place."* That rule sat in prose with nothing behind it, which is the
/// condition `.github/pull_request_template.md` was itself written to fix —
/// a checkpoint nobody is forced to answer is a checkpoint nobody answers.
///
/// The cost of getting this wrong is not a failed build. A contribution merged
/// without a sign-off cannot be relicensed later without tracking down its
/// author, and that option disappears silently and permanently.
///
/// The owner and the project's automation are exempt, because a CLA is an
/// agreement with an outside party and neither is one. Who counts is declared
/// in `.github/cla-exempt.txt`, not decided here.
#[test]
fn outside_contributions_carry_a_cla_sign_off() {
    let Some(commits) = commits_with_authors() else {
        return;
    };
    let exempt = cla_exempt();

    let mut missing: Vec<String> = Vec::new();

    for (hash, name, email, body) in &commits {
        if is_tool_generated(body.lines().next().unwrap_or_default()) {
            continue;
        }
        if exempt.iter().any(|e| e == name || e == email) {
            continue;
        }
        // Matched on the email, which is the identity `git commit -s` writes
        // and the one that can actually be traced back to a person. A name
        // collides; an address is how you reach whoever has to agree.
        let signed = body
            .lines()
            .filter_map(|l| l.trim().strip_prefix("Signed-off-by:"))
            .any(|trailer| trailer.contains(&format!("<{email}>")));

        if !signed {
            missing.push(format!("  {}  {name} <{email}>", &hash[..8]));
        }
    }

    assert!(
        missing.is_empty(),
        "these commits have no CLA sign-off matching their author:\n\n{}\n\n\
         Every outside contribution needs one — see CLA.md. Add it with:\n  \
         git commit -s   (or `git rebase --signoff main` for a branch)\n\n\
         If the author is a maintainer or automation, add the identity to\n  \
         .github/cla-exempt.txt\n",
        missing.join("\n")
    );
}
