// press/ + [press] + [brand]  →  one typed module the press page renders.
//
// The press room is a derivation, not a page someone maintains. A press kit
// that is hand-written drifts from the brand it describes: the boilerplate
// keeps a company name that changed, the fast facts keep a headcount from two
// years ago, and the logo section links a file that was redrawn. Every one of
// those is a wrong fact in circulation, because a press kit's whole purpose is
// to be copied.
//
// So the facts come from the declarations that already own them — the company
// name and domain from `[brand]`, the logo from the two brand primitives — and
// only the prose a person must write lives in `press/`.
import { readFileSync, readdirSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname } from "node:path";

const at = (p) => new URL(`../${p}`, import.meta.url);
const read = (p) => readFileSync(at(p), "utf8");

/**
 * Minimal TOML reach-in: the block and keys we need, nothing more.
 *
 * Parsed line by line rather than with one big regex. The regex version had two
 * bugs and both were silent:
 *
 *   · It ended the block with a `(?=^\[|\Z)` lookahead. **`\Z` is not a JS
 *     escape** — it is a literal `Z` — so the block stopped at the first
 *     capital Z in any value. It was found because a spokesperson named
 *     Zdravković came out of the pipeline as `"Aleksa`.
 *   · It stripped `#` to the end of line from every value, to drop trailing
 *     comments. That corrupts any quoted value containing a `#`, which is
 *     every hex colour — and `[brand]` is full of them.
 *
 * A quoted value is taken verbatim. Only an unquoted one can carry a trailing
 * comment, so only an unquoted one is stripped.
 */
function tomlBlock(src, name) {
  const out = {};
  let inside = false;
  for (const raw of src.split("\n")) {
    const line = raw.trim();
    if (/^\[[^\]]+\]$/.test(line)) {
      inside = line === `[${name}]`;
      continue;
    }
    if (!inside || !line || line.startsWith("#")) continue;
    const kv = raw.match(/^\s*([A-Za-z_][\w-]*)\s*=\s*(.+?)\s*$/);
    if (!kv) continue;
    let v = kv[2].trim();
    if (v.startsWith('"') && v.endsWith('"')) v = v.slice(1, -1);
    else v = v.replace(/\s*#.*$/, "").trim();
    out[kv[1]] = v;
  }
  return out;
}

const cfg = read("fiducial.toml");
const press = tomlBlock(cfg, "press");
const brand = tomlBlock(cfg, "brand");

/** Strip HTML comments — they are guidance for the writer, not content. */
const decomment = (s) => s.replace(/<!--[\s\S]*?-->/g, "").trim();

/** `## name` sections → { name: body }. */
function sections(md) {
  const out = {};
  const parts = decomment(md).split(/^##\s+/m).slice(1);
  for (const p of parts) {
    const nl = p.indexOf("\n");
    out[p.slice(0, nl).trim()] = p.slice(nl + 1).trim();
  }
  return out;
}

/** `key: value` lines → ordered pairs. Order is editorial, so it is kept. */
function pairs(md) {
  return decomment(md).split("\n").map((l) => l.match(/^([^:]+):\s*(.+)$/))
    .filter(Boolean).map((m) => ({ label: m[1].trim(), value: m[2].trim() }));
}

/** `---` frontmatter + body. */
function frontmatter(md) {
  const m = md.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!m) return { meta: {}, body: decomment(md) };
  const meta = {};
  for (const line of m[1].split("\n")) {
    const kv = line.match(/^([A-Za-z_][\w-]*):\s*(.*)$/);
    if (kv) meta[kv[1]] = kv[2].trim();
  }
  return { meta, body: decomment(m[2]) };
}

const boilerplate = sections(read("press/boilerplate.md"));
const facts = pairs(read("press/facts.md"));

const dir = at("press/stories");
const stories = (existsSync(dir) ? readdirSync(dir) : [])
  .filter((f) => f.endsWith(".md")).sort()
  .map((f) => {
    const { meta, body } = frontmatter(readFileSync(new URL(`press/stories/${f}`, at("")), "utf8"));
    return { slug: f.replace(/\.md$/, ""), title: meta.title ?? f, angle: meta.angle ?? "",
             date: meta.date ?? "", summary: meta.summary ?? "", body };
  });

const out = {
  pressEmail: press.press_email ?? "",
  founded: press.founded ?? "",
  hq: press.hq ?? "",
  spokesperson: press.spokesperson ?? "",
  legalName: brand.legal_name ?? "",
  tradingName: brand.trading_name ?? "",
  domain: brand.domain ?? "",
  boilerplate, facts, stories,
};

const lines = [
  "// Generated by `fid derive` (pipeline: press) from press/ and fiducial.toml.",
  "// Do not edit — edit the declarations and re-derive.",
  "//",
  "// A press kit exists to be copied, so a stale fact here becomes a wrong fact",
  "// in someone else's article, where you cannot correct it. Everything a",
  "// declaration already owns is read from that declaration, never retyped.",
  "",
  `export const press = ${JSON.stringify(out, null, 2)} as const`,
  "",
  "export type Story = (typeof press.stories)[number]",
  "",
];
const target = "apps/web/src/generated/press.ts";
mkdirSync(dirname(at(target).pathname), { recursive: true });
writeFileSync(at(target), lines.join("\n"));
console.log(`wrote ${target} (${stories.length} story/stories)`);
