#!/usr/bin/env python3
"""Vendor every declared part's KiCad component into hardware/lib/.

    python3 hardware/parts.py sync       resolve, copy, fetch; write manifest.json
    python3 hardware/parts.py check      fail if hardware/lib/ does not match the declaration

Platform-owned (installed by `fid add capability hardware`).

A part is not a box someone typed. It is a component in the formats the EDA
world already uses — a KiCad symbol, a KiCad footprint, a STEP model — taken
from a standard source, never redrawn. A part in hardware/product.toml names
them by library id:

    symbol    = "Regulator_Linear:AMS1117-3.3"
    footprint = "Package_DFN_QFN:QFN-20-1EP_3.5x3.5mm_P0.5mm_EP2x2mm"

`sync` copies them into the repository, so the product builds the same on a
laptop, in CI and in a cloud session, with no KiCad library installed:

    hardware/lib/footprints/<name>.kicad_mod
    hardware/lib/symbols.kicad_sym           every declared symbol, one library
    hardware/lib/3d/<name>.step              the footprint's own model
    hardware/lib/datasheets/<name>.pdf       the manufacturer's datasheet, from `datasheet = "<url>"`
    hardware/lib/datasheets/<name>.txt       its text, for an agent to search (needs pypdf)
    hardware/lib/manifest.json               where each file came from, and its hash
    hardware/lib/PARTS.md                    every part on one page: what it is, its files, its pins

PARTS.md is the hardware's context for a person or an agent: the one place
that says, per part, which symbol, footprint, model and datasheet it uses and
what each pin connects to, with links to the files. It is regenerated by every
`sync`, and `check` fails when it is stale.

A datasheet the network cannot reach is reported, never invented: download it
by hand to hardware/vendor/datasheets/<name>.pdf (vendor first, as for every
other file) and sync again.

fid-hardware then reads the footprint — the courtyard is the part's size, the
pads are its pins — and tracks the vendored files as inputs, so a changed
footprint fails `fid derive --check` by name. cad.py places the real model.

Sources, in order:

1. hardware/vendor/ — the product's own libraries, laid out as KiCad lays out
   its own (`<Lib>.pretty/<Name>.kicad_mod`, `<Lib>.kicad_sym`,
   `<Lib>.3dshapes/<Name>.step`), each with a SOURCES.md saying where every
   number came from. For a part the official libraries lack: a module whose
   land pattern is taken from a board that uses it, a symbol from an openly
   licensed library. Never a drawing from memory.
2. the KiCad libraries installed on this machine (KICAD7_FOOTPRINT_DIR /
   KICAD7_SYMBOL_DIR, default /usr/share/kicad/...);
3. the KiCad 3D-model repository for the model, at the tag matching the
   footprints.

What cannot be resolved is reported, not invented. A footprint whose model
no library ships is built by cad.py from the footprint itself — its fab
outline, its pads, the declared height — and the build says so.
"""

from __future__ import annotations

import datetime
import hashlib
import json
import os
import re
import shutil
import sys
import tomllib
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DECL = ROOT / "hardware" / "product.toml"
LIB = ROOT / "hardware" / "lib"
VENDOR = ROOT / "hardware" / "vendor"
FP_DIR = Path(os.environ.get("KICAD7_FOOTPRINT_DIR", "/usr/share/kicad/footprints"))
SYM_DIR = Path(os.environ.get("KICAD7_SYMBOL_DIR", "/usr/share/kicad/symbols"))
MODEL_TAG = os.environ.get("KICAD_LIB_TAG", "7.0.11")
MODEL_URL = "https://gitlab.com/kicad/libraries/kicad-packages3D/-/raw/{tag}/{lib}.3dshapes/{name}.step"


def sha(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def split_id(lib_id: str) -> tuple[str, str]:
    if ":" not in lib_id:
        raise SystemExit(f"`{lib_id}` is not a library id — expected Library:Name")
    lib, name = lib_id.split(":", 1)
    return lib, name


def symbol_block(text: str, name: str) -> str | None:
    """The whole `(symbol "name" …)` block at top level of a .kicad_sym, by paren matching."""
    m = re.search(r'\n\s*\(symbol "' + re.escape(name) + r'"', text)
    if not m:
        return None
    i = text.index("(", m.start())
    depth = 0
    in_str = False
    for j in range(i, len(text)):
        c = text[j]
        if c == '"' and text[j - 1] != "\\":
            in_str = not in_str
        elif not in_str:
            if c == "(":
                depth += 1
            elif c == ")":
                depth -= 1
                if depth == 0:
                    return text[i : j + 1]
    return None


def fetch(url: str, dest: Path) -> str | None:
    try:
        with urllib.request.urlopen(url, timeout=60) as r:
            dest.write_bytes(r.read())
        return None
    except Exception as e:  # noqa: BLE001 — reported, not raised
        return f"{type(e).__name__}: {e}"


def datasheet_name(part: dict) -> str:
    """The file a part's datasheet is kept as: its MPN, else its id."""
    return re.sub(r"[^A-Za-z0-9._-]+", "_", part.get("mpn") or part["id"])


def pdf_text(pdf: Path, txt: Path) -> str | None:
    """A text copy of a PDF, so an agent can grep the datasheet. pypdf if installed."""
    try:
        from pypdf import PdfReader  # type: ignore
    except ImportError:
        return "pypdf is not installed (pip install pypdf) — no text copy"
    except (KeyboardInterrupt, SystemExit):
        raise
    except BaseException as e:  # noqa: BLE001 — a broken install panics, not raises
        return f"pypdf failed to load ({type(e).__name__}) — no text copy"
    try:
        pages = PdfReader(str(pdf)).pages
        txt.write_text("\n\n".join(f"--- page {i + 1} ---\n{p.extract_text() or ''}" for i, p in enumerate(pages)))
        return None
    except Exception as e:  # noqa: BLE001 — reported, not raised
        return f"{type(e).__name__}: {e}"


LCSC_DETAIL = "https://wmsc.lcsc.com/ftps/wm/product/detail?productCode={code}"


def lcsc_datasheet(code: str) -> tuple[str | None, str | None]:
    """The datasheet URL LCSC lists for a part number: (url, error)."""
    try:
        with urllib.request.urlopen(LCSC_DETAIL.format(code=code), timeout=30) as r:
            url = (json.loads(r.read()).get("result") or {}).get("pdfUrl")
        return (url, None) if url else (None, "LCSC lists no datasheet")
    except Exception as e:  # noqa: BLE001 — reported, not raised
        return None, f"{type(e).__name__}: {e}"


def datasheet(part: dict, problems: list[str], earlier: dict) -> dict | None:
    """Declared `datasheet`, else the one LCSC lists for the part's `lcsc` number."""
    url = part.get("datasheet") or earlier.get("url")
    if not url and part.get("lcsc") and part.get("status") != "assumed":
        url, err = lcsc_datasheet(part["lcsc"])
        if err:
            name = datasheet_name(part)
            if (VENDOR / "datasheets" / f"{name}.pdf").exists():
                url = "vendored"
            else:
                problems.append(
                    f"{part['id']}: no datasheet URL — declare `datasheet`, or let LCSC {part['lcsc']} answer ({err}); "
                    f"or save it as hardware/vendor/datasheets/{name}.pdf"
                )
                return {"url": None, "file": None}
    if not url:
        return None
    name = datasheet_name(part)
    (LIB / "datasheets").mkdir(parents=True, exist_ok=True)
    dest = LIB / "datasheets" / f"{name}.pdf"
    own = VENDOR / "datasheets" / f"{name}.pdf"
    entry: dict = {"url": url, "file": f"datasheets/{name}.pdf"}
    if part.get("datasheet") and earlier.get("url") not in (None, part["datasheet"]):
        dest.unlink(missing_ok=True)  # the declaration names a different document now
    if own.exists():
        shutil.copyfile(own, dest)
        entry["from"] = str(own.relative_to(ROOT))
    elif url == "vendored":
        problems.append(f"{part['id']}: datasheet named vendored but hardware/vendor/datasheets/{name}.pdf is gone")
        return {"url": None, "file": None}
    elif not dest.exists():
        err = fetch(url, dest)
        if err is None and not dest.read_bytes().startswith(b"%PDF"):
            err = "the URL did not return a PDF"
        if err:
            dest.unlink(missing_ok=True)
            problems.append(f"{part['id']}: datasheet {url} could not be fetched ({err}) — save it as hardware/vendor/datasheets/{name}.pdf")
            return {"url": url, "file": None}
        entry["from"] = url
        entry["fetched"] = datetime.date.today().isoformat()
    else:
        entry["from"] = "fetched earlier"
    entry["sha256"] = sha(dest)
    txt = dest.with_suffix(".txt")
    if not txt.exists() or txt.stat().st_mtime < dest.stat().st_mtime:
        err = pdf_text(dest, txt)
        if err:
            problems.append(f"{part['id']}: datasheet text: {err}")
    if txt.exists():
        entry["text"] = f"datasheets/{name}.txt"
    return entry


def parts_md(decl: dict, manifest: dict) -> str:
    """Every part on one page — the hardware's context for a person or an agent."""
    rel = lambda f: f"[{f}]({f})"  # noqa: E731 — links resolve from hardware/lib/
    out = [
        "# Parts",
        "",
        "Generated by `python3 hardware/parts.py sync` from `hardware/product.toml` — do not edit.",
        "Per part: what it is, where it came from, its KiCad files, its datasheet, and what each pin connects to.",
        "Paths are relative to `hardware/lib/`. Search a datasheet's `.txt` before reading the PDF.",
        "",
        "| id | part | value | MPN | LCSC | status | datasheet |",
        "|---|---|---|---|---|---|---|",
    ]
    for part in decl.get("part", []):
        e = manifest["parts"].get(part["id"], {})
        ds = e.get("datasheet") or {}
        dcell = rel(ds["file"]) if ds.get("file") else ("**missing**" if ds else "—")
        out.append(
            f"| `{part['id']}` | {part.get('name', '')} | {part.get('value', '')} | {part.get('mpn', '')} | "
            f"{part.get('lcsc', '')} | {part.get('status', '')} | {dcell} |"
        )
    for part in decl.get("part", []):
        e = manifest["parts"].get(part["id"], {})
        out += ["", f"## `{part['id']}` — {part.get('name', '')}", ""]
        facts = [
            ("place / mount", f"{part.get('place', '')} / {part.get('mount', '')}"),
            ("manufacturer", part.get("manufacturer")),
            ("MPN", part.get("mpn")),
            ("second source", part.get("second_source")),
            ("LCSC", part.get("lcsc")),
            ("value", part.get("value")),
            ("quantity", part.get("qty")),
            ("status", part.get("status")),
            ("dimensions from", part.get("dims_from") or ("footprint" if part.get("footprint") else None)),
            ("source", part.get("source_url")),
            ("still to settle", part.get("settle_by")),
        ]
        for k, v in facts:
            if v not in (None, ""):
                out.append(f"- **{k}:** {v}")
        if "symbol" in e:
            out.append(f"- **symbol:** `{e['symbol']['id']}` (in [symbols.kicad_sym](symbols.kicad_sym))")
        if "footprint" in e:
            out.append(f"- **footprint:** `{e['footprint']['id']}` → {rel('footprints/' + split_id(e['footprint']['id'])[1] + '.kicad_mod')}")
        if "model" in e:
            out.append(f"- **3D model:** {rel(e['model']['file'])}")
        ds = e.get("datasheet")
        if ds:
            if ds.get("file"):
                text = f", text {rel(ds['text'])}" if ds.get("text") else ""
                out.append(f"- **datasheet:** {rel(ds['file'])}{text} — from {ds['url']}")
            else:
                out.append(f"- **datasheet:** not yet fetched — {ds['url'] or 'no URL known'}; see `problems` in manifest.json")
        pins = part.get("pins") or {}
        if pins:
            out.append("- **pins → nets:** " + ", ".join(f"`{k}` → `{v}`" for k, v in pins.items()))
        if part.get("nets"):
            out.append("- **pads → nets:** " + ", ".join(f"{i + 1} → `{n}`" for i, n in enumerate(part["nets"])))
        if part.get("near"):
            out.append(f"- **placed near:** `{part['near']}`")
    return "\n".join(out) + "\n"


def sync() -> int:
    decl = tomllib.loads(DECL.read_text())
    (LIB / "footprints").mkdir(parents=True, exist_ok=True)
    (LIB / "3d").mkdir(parents=True, exist_ok=True)
    before = json.loads((LIB / "manifest.json").read_text()) if (LIB / "manifest.json").exists() else {"parts": {}}
    manifest: dict = {"generated_by": "hardware/parts.py sync — do not edit", "kicad_lib_tag": MODEL_TAG, "parts": {}}
    symbols: list[str] = []
    seen: set[str] = set()
    problems: list[str] = []

    for part in decl.get("part", []):
        entry: dict = {}
        fp_id = part.get("footprint")
        if fp_id:
            lib, name = split_id(fp_id)
            own = VENDOR / f"{lib}.pretty" / f"{name}.kicad_mod"
            src = own if own.exists() else FP_DIR / f"{lib}.pretty" / f"{name}.kicad_mod"
            dest = LIB / "footprints" / f"{name}.kicad_mod"
            own_model = VENDOR / f"{lib}.3dshapes" / f"{name}.step"
            if own.exists():
                shutil.copyfile(own, dest)
                entry["footprint"] = {"id": fp_id, "from": str(own.relative_to(ROOT)), "sha256": sha(dest)}
                if own_model.exists():
                    mdest = LIB / "3d" / f"{name}.step"
                    shutil.copyfile(own_model, mdest)
                    entry["model"] = {"from": str(own_model.relative_to(ROOT)), "sha256": sha(mdest), "file": f"3d/{name}.step"}
            elif src.exists():
                shutil.copyfile(src, dest)
                entry["footprint"] = {"id": fp_id, "from": str(src), "sha256": sha(dest)}
                m = re.search(r"\(model\s+\"?\$\{KICAD\d_3DMODEL_DIR\}/([^/\"]+)\.3dshapes/([^\"\s)]+)\.(wrl|step)", src.read_text())
                if m:
                    mdest = LIB / "3d" / f"{m.group(2)}.step"
                    url = MODEL_URL.format(tag=MODEL_TAG, lib=m.group(1), name=m.group(2))
                    err = None if mdest.exists() else fetch(url, mdest)
                    if err:
                        mdest.unlink(missing_ok=True)
                        problems.append(f"{part['id']}: no 3D model at {url} ({err}) — cad.py builds one from the footprint")
                    else:
                        entry["model"] = {"from": url, "sha256": sha(mdest), "file": f"3d/{m.group(2)}.step"}
            elif dest.exists():
                entry["footprint"] = {"id": fp_id, "from": "vendored earlier", "sha256": sha(dest)}
            else:
                problems.append(f"{part['id']}: footprint {fp_id} is not in {FP_DIR} (install kicad-footprints, or set KICAD7_FOOTPRINT_DIR)")
        elif part.get("lcsc") and part.get("place") == "board":
            problems.append(
                f"{part['id']}: no footprint declared; LCSC {part['lcsc']} could come from easyeda2kicad "
                f"(`pip install easyeda2kicad; easyeda2kicad --full --lcsc_id={part['lcsc']} --output hardware/lib/lcsc`), "
                "which needs easyeda.com reachable"
            )
        sym_id = part.get("symbol")
        if not sym_id and part.get("mount") == "pads" and part.get("nets"):
            # Wire pads are a connector in the schematic: KiCad's generic one.
            sym_id = f"Connector_Generic:Conn_01x{len(part['nets']):02d}"
        if sym_id:
            lib, name = split_id(sym_id)
            own = VENDOR / f"{lib}.kicad_sym"
            src = own if own.exists() and symbol_block(own.read_text(), name) else SYM_DIR / f"{lib}.kicad_sym"
            block = symbol_block(src.read_text(), name) if src.exists() else None
            if block:
                if "(extends " in block[:400]:
                    problems.append(f"{part['id']}: symbol {sym_id} extends another symbol; vendor its parent too")
                # One library entry per symbol, however many parts use it;
                # named by the full id, so Device:R and a vendor R never collide.
                if sym_id not in seen:
                    seen.add(sym_id)
                    symbols.append(block.replace(f'(symbol "{name}"', f'(symbol "{sym_id}"', 1))
                entry["symbol"] = {"id": sym_id, "from": str(src.relative_to(ROOT)) if src.is_relative_to(ROOT) else str(src)}
            else:
                problems.append(f"{part['id']}: symbol {sym_id} not found in {src}")
        ds = datasheet(part, problems, (before["parts"].get(part["id"], {}).get("datasheet") or {}))
        if ds:
            entry["datasheet"] = ds
        if entry:
            manifest["parts"][part["id"]] = entry

    # A part no longer declared takes its vendored files with it: a stale
    # footprint in lib/ is a component the product no longer has.
    kept = {f"footprints/{split_id(e['footprint']['id'])[1]}.kicad_mod" for e in manifest["parts"].values() if "footprint" in e}
    kept |= {e["model"]["file"] for e in manifest["parts"].values() if "model" in e}
    kept |= {e["datasheet"][k] for e in manifest["parts"].values() for k in ("file", "text") if e.get("datasheet", {}).get(k)}
    for sub in ("footprints", "3d", "datasheets"):
        if not (LIB / sub).is_dir():
            continue
        for f in (LIB / sub).iterdir():
            if f"{sub}/{f.name}" not in kept:
                f.unlink()
                print(f"removed {f.relative_to(ROOT)} (no longer declared)")
    (LIB / "symbols.kicad_sym").write_text(
        "(kicad_symbol_lib (version 20220914) (generator fid_parts)\n  " + "\n  ".join(symbols) + "\n)\n"
    )
    manifest["problems"] = problems
    (LIB / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    (LIB / "PARTS.md").write_text(parts_md(decl, manifest))
    for p in problems:
        print(f"unresolved: {p}", file=sys.stderr)
    print(f"vendored {len(manifest['parts'])} part(s) into hardware/lib/; {len(problems)} unresolved")
    return 0


def check() -> int:
    decl = tomllib.loads(DECL.read_text())
    man = json.loads((LIB / "manifest.json").read_text()) if (LIB / "manifest.json").exists() else {"parts": {}}
    bad = []
    for part in decl.get("part", []):
        fp = part.get("footprint")
        if fp:
            got = man["parts"].get(part["id"], {}).get("footprint", {})
            name = split_id(fp)[1]
            f = LIB / "footprints" / f"{name}.kicad_mod"
            if got.get("id") != fp or not f.exists() or sha(f) != got.get("sha256"):
                bad.append(f"{part['id']}: {fp} is not vendored as declared — run python3 hardware/parts.py sync")
        ds = man["parts"].get(part["id"], {}).get("datasheet") or {}
        if ds.get("file"):
            f = LIB / ds["file"]
            if not f.exists() or sha(f) != ds.get("sha256"):
                bad.append(f"{part['id']}: datasheet {ds['file']} does not match the manifest — run python3 hardware/parts.py sync")
        elif part.get("datasheet") and ds.get("url") != part["datasheet"]:
            bad.append(f"{part['id']}: datasheet {part['datasheet']} is declared but not synced — run python3 hardware/parts.py sync")
    if (LIB / "PARTS.md").read_text() != parts_md(decl, man) if (LIB / "PARTS.md").exists() else True:
        bad.append("hardware/lib/PARTS.md is stale — run python3 hardware/parts.py sync")
    missing = [p for p in man.get("problems", []) if "datasheet" in p]
    for m in missing:
        print(f"note: {m}", file=sys.stderr)
    for b in bad:
        print(b, file=sys.stderr)
    return 1 if bad else 0


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "sync"
    sys.exit({"sync": sync, "check": check}.get(cmd, lambda: (print(__doc__), 2)[1])())
