// The two logo primitives → one generated module everything else reads.
//
// `brand/icon.svg` and `brand/wordmark.svg` are the source of truth for the
// mark. This script extracts their geometry into
// `apps/web/src/generated/logo.ts` so React renders the same paths the SVG
// files carry, rather than a second copy typed into a component.
//
// It exists because the copy was real and it was wrong: `brand/favicon.svg`
// held the flame from before it was redrawn, and its own comment said the
// duplication was cheaper than deriving it. It was not — the site shipped the
// old mark at 16px while the wordmark on the page showed the new one, and
// nothing could have told anyone.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

const read = (p) => readFileSync(new URL(`../${p}`, import.meta.url), "utf8");

/**
 * Reject a primitive that is not well-formed XML.
 *
 * A `.svg` file is served as `image/svg+xml` and parsed strictly, so a browser
 * will refuse to render it — silently, as a broken image — where an HTML parser
 * would have shrugged. The failure that prompted this check: a `--` inside an
 * XML comment, which is illegal and is exactly what you get from writing a CLI
 * flag like `derive --check` into a comment explaining the file.
 *
 * Only the comment-level trap is checked here, because it is the one that a
 * human writing documentation will hit again and again.
 */
function assertWellFormed(name, svg) {
  for (const m of svg.matchAll(/<!--([\s\S]*?)-->/g)) {
    if (m[1].includes("--")) {
      throw new Error(
        `${name}: an XML comment contains "--", which is not legal and makes ` +
          `the file unrenderable. Rewrite the comment (a CLI flag like ` +
          `\`--check\` is the usual culprit).`,
      );
    }
  }
  if (!/<svg[\s>]/.test(svg)) throw new Error(`${name}: no <svg> element`);
}

/** Pull `<path d="…">`/`<polygon points="…">` and the viewBox out of an SVG. */
function parse(svg) {
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1];
  if (!viewBox) throw new Error("no viewBox");
  const layer = (id) => {
    const g = svg.match(new RegExp(`<g[^>]*data-layer="${id}"[^>]*>([\\s\\S]*?)</g>`))?.[1];
    if (g === undefined) return null;
    return {
      paths: [...g.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]),
      polygons: [...g.matchAll(/<polygon[^>]*\spoints="([^"]+)"/g)].map((m) => m[1]),
    };
  };
  return { viewBox, layer };
}

const iconSvg = read("brand/icon.svg");
const wordSvg = read("brand/wordmark.svg");
assertWellFormed("brand/icon.svg", iconSvg);
assertWellFormed("brand/wordmark.svg", wordSvg);
const icon = parse(iconSvg);
const word = parse(wordSvg);

const flame = icon.layer("flame");
const letters = word.layer("letters");
const device = word.layer("device");
if (!flame || !letters || !device) {
  throw new Error("a primitive is missing a data-layer group (flame/letters/device)");
}

// A square box tight to the flame and centred on its own width, for the places
// the mark is used bare (an app icon slot, a bullet, a favicon caption). Derived
// from the path rather than typed, so it follows the drawing if the flame moves.
function flameBox(d) {
  const n = d.match(/-?\d+(?:\.\d+)?/g).map(Number);
  const xs = n.filter((_, i) => i % 2 === 0);
  const ys = n.filter((_, i) => i % 2 === 1);
  const [x0, x1] = [Math.min(...xs), Math.max(...xs)];
  const [y0, y1] = [Math.min(...ys), Math.max(...ys)];
  const size = Math.max(x1 - x0, y1 - y0);
  const cx = (x0 + x1) / 2;
  return `${+(cx - size / 2).toFixed(4)} ${y0} ${size} ${size}`;
}

const lines = [
  "// Generated by `node scripts/derive-logo.mjs` from the two logo primitives.",
  "// Do not edit — edit brand/icon.svg or brand/wordmark.svg and re-derive.",
  "//",
  "// There are exactly two logo primitives and everything else is a view of",
  "// them: the favicon, the app icon, the wordmark in the nav and the footer,",
  "// the mark on a slide. A component that types out its own path data is a",
  "// third logo that nobody will remember to update.",
  "",
  `export const iconViewBox = ${JSON.stringify(icon.viewBox)} as const`,
  "",
  "/** Square and tight to the flame, in wordmark coordinates. */",
  `export const flameViewBox = ${JSON.stringify(flameBox(flame.paths.join(" ")))} as const`,
  `export const wordmarkViewBox = ${JSON.stringify(word.viewBox)} as const`,
  "",
  "/** The flame. Outer contour then counter — fill-rule evenodd. */",
  `export const FLAME = ${JSON.stringify(flame.paths.join(" "))}`,
  "",
  "/** `utreach`, lifted unmodified from the Outreach wordmark. */",
  `export const LETTERS = ${JSON.stringify(letters.paths, null, 2)} as const`,
  "",
  "/** The radio-transmission device on the `h`. */",
  `export const DEVICE = ${JSON.stringify(device.polygons, null, 2)} as const`,
  "",
];
const out = "apps/web/src/generated/logo.ts";
mkdirSync(dirname(new URL(`../${out}`, import.meta.url).pathname), { recursive: true });
writeFileSync(new URL(`../${out}`, import.meta.url), lines.join("\n"));
console.log(`wrote ${out}`);
