//! **`fiducial-wasm`** — WASM bindings for `fiducial-core`.
//!
//! This crate wraps [`fiducial_core`] with `wasm-bindgen` so that JavaScript
//! running in a browser, a Cloudflare Worker, or a Node.js process can call
//! the same logic that runs natively in Tauri and on firmware.
//!
//! # Building
//!
//! ```sh
//! # Install wasm-pack once:
//! cargo install wasm-pack
//!
//! # Build the WASM module + JS/TS glue:
//! wasm-pack build crates/fiducial-wasm --target bundler --out-dir ../../packages/wasm-bridge/src/wasm
//! ```
//!
//! # Type generation
//!
//! TypeScript types are generated by `ts-rs` (Phase 3+). Until then, the
//! JS/TS glue produced by `wasm-pack` is the authoritative surface — do not
//! hand-write types that duplicate what wasm-bindgen already knows.
//!
//! # Design note
//!
//! The WASM boundary is crossed **rarely, with meaningful payloads, not
//! constantly with small ones**. A chatty Rust↔JS API is a design error, not
//! an inherent WASM cost (spec §4.1).

use wasm_bindgen::prelude::*;

// ── Version ─────────────────────────────────────────────────────────────────

/// Returns the fiducial-core version string.
///
/// ```js
/// import init, { fiducialVersion } from "@fiducial/wasm-bridge";
/// await init();
/// console.log(fiducialVersion()); // "0.1.0"
/// ```
#[wasm_bindgen(js_name = fiducialVersion)]
pub fn fiducial_version() -> String {
    fiducial_core::version().into()
}

// ── DeviceId ─────────────────────────────────────────────────────────────────

/// JS-visible wrapper around [`fiducial_core::DeviceId`].
///
/// ```js
/// const id = new DeviceId(new Uint8Array([1, 2, 3, 4, 5, 6, 7, 8]));
/// console.log(id.isZero()); // false
/// ```
#[wasm_bindgen]
pub struct DeviceId(fiducial_core::DeviceId);

#[wasm_bindgen]
impl DeviceId {
    /// Construct from exactly 8 bytes (pass a `Uint8Array` from JS).
    ///
    /// Throws a JS `Error` if the slice is not exactly 8 bytes.
    #[wasm_bindgen(constructor)]
    pub fn new(bytes: &[u8]) -> Result<DeviceId, JsError> {
        let arr: [u8; 8] = bytes
            .try_into()
            .map_err(|_| JsError::new("DeviceId requires exactly 8 bytes"))?;
        Ok(DeviceId(fiducial_core::DeviceId::new(arr)))
    }

    /// Returns the uninitialized sentinel (all bytes zero).
    #[wasm_bindgen(js_name = zero)]
    pub fn zero() -> DeviceId {
        DeviceId(fiducial_core::DeviceId::ZERO)
    }

    /// `true` when all bytes are zero — the uninitialized sentinel.
    ///
    /// A device that has not stored its UID returns `true` here. Callers
    /// should gate registration and association on this.
    #[wasm_bindgen(js_name = isZero)]
    pub fn is_zero(&self) -> bool {
        self.0.is_zero()
    }

    /// Returns the raw bytes as a `Uint8Array`.
    #[wasm_bindgen(js_name = toBytes)]
    pub fn to_bytes(&self) -> Vec<u8> {
        self.0.as_bytes().to_vec()
    }
}

// ── TypeScript type generation (Phase 9) ─────────────────────────────────────
//
// Run `cargo test --features ts -p fiducial-wasm` to regenerate
// packages/wasm-bridge/src/generated.ts.  Guard-blocked: never hand-write types
// that cross this boundary (spec §7, Appendix A).

#[cfg(feature = "ts")]
mod ts_export {
    use ts_rs::TS;

    /// TypeScript shape of a device identifier exchanged over the wire.
    #[derive(TS)]
    #[ts(export, export_to = "../../../packages/wasm-bridge/src/generated.ts")]
    #[allow(dead_code)]
    struct DeviceIdTs {
        /// Raw bytes, big-endian, 8 octets.
        bytes: Vec<u8>,
    }

    /// Platform version reported by every artifact.
    #[derive(TS)]
    #[ts(export, export_to = "../../../packages/wasm-bridge/src/generated.ts")]
    #[allow(dead_code)]
    struct PlatformVersion {
        /// Semver string, e.g. "0.1.0".
        version: String,
    }

    #[test]
    fn export_ts_types() {
        DeviceIdTs::export_all().expect("TS type export failed");
        PlatformVersion::export_all().expect("TS type export failed");
    }
}

// ── WASM tests ───────────────────────────────────────────────────────────────
// Run with: wasm-pack test --node crates/fiducial-wasm

#[cfg(test)]
mod tests {
    use super::*;
    use wasm_bindgen_test::wasm_bindgen_test;

    wasm_bindgen_test::wasm_bindgen_test_configure!(run_in_node_experimental);

    #[wasm_bindgen_test]
    fn version_nonempty() {
        assert!(!fiducial_version().is_empty());
    }

    #[wasm_bindgen_test]
    fn device_id_zero_sentinel() {
        let id = DeviceId::zero();
        assert!(id.is_zero());
    }

    #[wasm_bindgen_test]
    fn device_id_from_bytes() {
        let bytes = [1u8, 2, 3, 4, 5, 6, 7, 8];
        let id = DeviceId::new(&bytes).unwrap();
        assert!(!id.is_zero());
        assert_eq!(id.to_bytes(), bytes);
    }

    #[wasm_bindgen_test]
    fn device_id_wrong_length_errors() {
        let result = DeviceId::new(&[1u8, 2, 3]);
        assert!(result.is_err());
    }
}
