/**
 * Board marketing page — renders the enclosure generated by `fid derive`.
 *
 * The GLB is not committed by hand: `fid derive` writes it from the `outline`
 * block declared in board/board.interface.json, sized by that board's tolerance
 * class. Copy the generated file into the app's public directory as part of
 * your build so this page serves the current geometry:
 *
 *   cp enclosure/board.glb apps/web/public/board.glb
 *
 * Requires the viewer package and its peer:
 *
 *   pnpm add @fiducial/viewer3d-react three
 */

'use client'

import { BoardViewer } from '@fiducial/viewer3d-react'

export default function BoardPage() {
  return (
    <main
      style={{
        maxWidth: '64rem',
        margin: '0 auto',
        padding: 'var(--fiducial-spacing-8, 2rem)',
      }}
    >
      <h1 style={{ marginBottom: 'var(--fiducial-spacing-2, 0.5rem)' }}>The board</h1>
      <p style={{ marginBottom: 'var(--fiducial-spacing-6, 1.5rem)', opacity: 0.8 }}>
        Enclosure generated directly from the board outline. Drag to orbit, scroll to zoom.
      </p>

      <BoardViewer
        src="/board.glb"
        width={800}
        height={500}
        style={{ borderRadius: 'var(--fiducial-radius-lg, 0.5rem)', overflow: 'hidden' }}
      />

      <p style={{ marginTop: 'var(--fiducial-spacing-4, 1rem)', fontSize: '0.875rem', opacity: 0.7 }}>
        Wall thickness and board clearance are derived from the manufacturing tolerance class
        declared alongside the outline — change the process and the geometry follows.
      </p>
    </main>
  )
}
