// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * TypeScript shape of a device identifier exchanged over the wire.
 */
export type DeviceIdTs = { 
/**
 * Raw bytes, big-endian, 8 octets.
 */
bytes: Array<number>, };

/**
 * Platform version reported by every artifact.
 */
export type PlatformVersion = { 
/**
 * Semver string, e.g. "0.1.0".
 */
version: string, };
