#!/usr/bin/env bash
#
# The grants schema, its row-level security policies, and the store's queries —
# against a real PostgreSQL server.
#
# Why this exists: `packages/identity/src/grants.test.js` runs the generated
# schema on real SQLite (`node:sqlite`), because D1 is SQLite. Node has no
# Postgres, so the Postgres half of the same derivation had no engine behind
# it — and the first thing that fact hid was a migration that does not run:
#
#   ERROR:  syntax error at or near "GLOB"
#
# and, once that was fixed, policies that parse fine and then refuse every
# query they are asked about:
#
#   ERROR:  infinite recursion detected in policy for relation "grants"
#
# Neither is visible to a test that only reads the generated text. So this runs
# it. CI does too — see the `identity` job, which starts a postgres:16 service.
#
# Usage (any reachable server; standard libpq env vars):
#
#   PGHOST=localhost PGPORT=5432 PGUSER=postgres PGPASSWORD=postgres \
#     scripts/verify-postgres.sh
#
# The connecting role must own what it creates; it is the RLS-exempt "service"
# side of the test, and `app_user` is the ordinary, policy-bound side.
set -euo pipefail

repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fid="$repo/target/debug/fid"
export PGDATABASE="${PGDATABASE:-postgres}"

psql_() { psql -X -q -v ON_ERROR_STOP=1 "$@"; }

fail=0
ok()   { printf '  ok    %s\n' "$1"; }
bad()  { printf '  FAIL  %s\n' "$1"; fail=1; }

# `expect <what> <wanted> <got>`
expect() { [ "$2" = "$3" ] && ok "$1" || bad "$1 — wanted [$2], got [$3]"; }

# Run SQL as the policy-bound role, with a JWT subject. One psql invocation is
# one session, so the SET ROLE and the query share it.
as_user() {
  psql -X -At -q -v ON_ERROR_STOP=1 \
    -c "SET ROLE app_user" \
    -c "SET request.jwt.claim.sub = '$1'" \
    -c "$2"
}

# `refused <label> <uuid> <sql>` — the policy must reject this.
refused() {
  if as_user "$2" "$3" >/dev/null 2>&1; then
    bad "$1 (it was allowed)"
  else
    ok "$1"
  fi
}

# ── The artifact under test, generated by the real binary ────────────────────

[ -x "$fid" ] || cargo build --manifest-path "$repo/Cargo.toml" -p fiducial-cli --bin fid

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
( cd "$work" && "$fid" new p >/dev/null )
product="$work/p"
( cd "$product" && "$fid" add identity >/dev/null )

# Postgres, with policies. Declared here rather than derived because the
# scaffold has no database vendor selected; a product on Supabase gets this
# from `[adapters] database` alone.
python3 - "$product/fiducial.toml" <<'PY'
import sys
p = sys.argv[1]
s = open(p).read().replace("[identity]", '[identity]\ndialect = "postgres"\nrls = true\naudit = true')
open(p, "w").write(s)
PY
( cd "$product" && "$fid" derive >/dev/null )

schema="$product/migrations/0001_grants.sql"
grep -q 'Dialect: postgres' "$schema" || { echo "not a postgres migration"; exit 1; }

echo "verifying $schema"

# ── A stand-in for the vendor's current-user function ────────────────────────
#
# `auth.uid()` is Supabase's. Its contract is all this needs: a STABLE function
# returning the signed-in user's UUID. Reading it from a GUC is how PostgREST
# supplies it, so this is the same shape rather than a mock.
psql_ <<'SQL'
DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;
CREATE SCHEMA IF NOT EXISTS auth;
CREATE OR REPLACE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS
  $$ SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_user') THEN
    CREATE ROLE app_user;
  END IF;
END $$;
GRANT USAGE ON SCHEMA public, auth TO app_user;
SQL

# ── The migration itself has to run ──────────────────────────────────────────

psql_ -f "$schema"
ok "the generated migration applies"

psql_ -c "GRANT SELECT, INSERT, UPDATE, DELETE ON grants TO app_user"

alice=11111111-1111-1111-1111-111111111111; alice_id=11111111111111111111111111111111
bob=22222222-2222-2222-2222-222222222222;   bob_id=22222222222222222222222222222222
carol=33333333-3333-3333-3333-333333333333; carol_id=33333333333333333333333333333333
dave_id=55555555555555555555555555555555

psql_ <<SQL
INSERT INTO grants VALUES
 ('user', '$alice_id', 'device', 'thermostat', 'owner',  now()),
 ('user', '$bob_id',   'device', 'thermostat', 'viewer', now()),
 ('user', '$carol_id', 'platform', '',         'admin',  now());
SQL

# ── The CHECK constraints are the identity model's variants ──────────────────

if psql_ -c "INSERT INTO grants VALUES ('device','00000000000000000000000000000000','device','x','viewer',now())" >/dev/null 2>&1
then bad "an all-zero principal id is refused (it was stored)"
else ok "an all-zero principal id is refused"
fi

if psql_ -c "INSERT INTO grants VALUES ('anonymous','$dave_id','device','x','viewer',now())" >/dev/null 2>&1
then bad "an anonymous principal is refused (it was stored)"
else ok "an anonymous principal is refused"
fi

# ── The policies, from each side ─────────────────────────────────────────────
#
# A SELECT that returns nothing and a SELECT that errors look alike from the
# outside, which is how the recursion bug survived being "written correctly" —
# so these count rows AND the refusals are separate, explicit cases.

expect "a viewer reads only their own grant" \
  "$bob_id" "$(as_user "$bob" "SELECT principal_id FROM grants")"

expect "an owner reads every grant over the resource they own" \
  "$alice_id
$bob_id" "$(as_user "$alice" "SELECT principal_id FROM grants ORDER BY 1")"

expect "a platform admin reads everything" \
  "3" "$(as_user "$carol" "SELECT count(*) FROM grants")"

expect "an unauthenticated session reads nothing" \
  "0" "$(as_user "" "SELECT count(*) FROM grants")"

refused "a viewer cannot grant" "$bob" \
  "INSERT INTO grants VALUES ('user','$dave_id','device','thermostat','viewer',now())"

# UPDATE is filtered rather than refused — the row is invisible to the policy,
# so the statement succeeds and changes nothing. What matters is the role.
as_user "$bob" "UPDATE grants SET role = 'owner' WHERE principal_id = '$bob_id'" >/dev/null
expect "a viewer cannot promote themselves" \
  "viewer" "$(psql -X -At -q -c "SELECT role FROM grants WHERE principal_id = '$bob_id'")"

as_user "$alice" \
  "INSERT INTO grants VALUES ('user','$dave_id','device','thermostat','member',now())" >/dev/null
expect "an owner can grant over their own resource" \
  "member" "$(psql -X -At -q -c "SELECT role FROM grants WHERE principal_id = '$dave_id'")"

refused "an owner cannot grant over a resource they do not administer" "$alice" \
  "INSERT INTO grants VALUES ('user','$dave_id','device','kettle','member',now())"

as_user "$alice" "DELETE FROM grants WHERE principal_id = '$bob_id'" >/dev/null
expect "an owner can revoke over their own resource" \
  "0" "$(psql -X -At -q -c "SELECT count(*) FROM grants WHERE principal_id = '$bob_id'")"

# ── The store's own SQL, in the dialect it renders for Postgres ──────────────
#
# `grants.test.js` asserts the *text* of these ($1, not ?); this asserts the
# server accepts them. Rendered by hand here because the store is TypeScript
# and this is psql — the pair of checks is what makes both meaningful.

expect "the store's grantsFor query runs as Postgres numbers it" \
  "$alice_id" "$(psql -X -At -q \
    -c "PREPARE g(text,text) AS SELECT principal_id FROM grants WHERE principal_kind = \$1 AND principal_id = \$2" \
    -c "EXECUTE g('user','$alice_id')")"

expect "the store's upsert runs, and replaces rather than duplicating" \
  "admin" "$(psql -X -At -q \
    -c "INSERT INTO grants
          (principal_kind, principal_id, resource_kind, resource_id, role, granted_at)
        VALUES ('user','$alice_id','device','thermostat','admin',now())
        ON CONFLICT (principal_kind, principal_id, resource_kind, resource_id)
        DO UPDATE SET role = excluded.role, granted_at = excluded.granted_at" \
    -c "SELECT role FROM grants WHERE principal_id = '$alice_id'")"

# ── Expiry and delegation, on the server rather than in a string ────────────
#
# These columns are new, and Postgres disagrees with SQLite about more of their
# spelling than is comfortable: SQLite has no BOOLEAN, and a CHECK spanning two
# nullable columns is the kind of thing that parses and then does nothing.

expect "an expiry stores and reads back as a number" \
  "1789516800000" "$(psql -X -At -q \
    -c "INSERT INTO grants
          (principal_kind, principal_id, resource_kind, resource_id, role,
           granted_at, expires_at)
        VALUES ('user','$bob_id','device','lamp','viewer',now(),1789516800000)" \
    -c "SELECT expires_at FROM grants WHERE principal_id = '$bob_id' AND resource_id = 'lamp'")"

expect "a permanent grant stores NULL, not zero" \
  "t" "$(psql -X -At -q -c \
    "SELECT expires_at IS NULL FROM grants
      WHERE principal_id = '$alice_id' AND resource_id = 'thermostat'")"

expect "a delegator stores and reads back whole" \
  "user|$alice_id" "$(psql -X -At -q \
    -c "INSERT INTO grants
          (principal_kind, principal_id, resource_kind, resource_id, role,
           granted_at, delegated_by_kind, delegated_by_id)
        VALUES ('user','$bob_id','device','kettle','admin',now(),'user','$alice_id')" \
    -c "SELECT delegated_by_kind || '|' || delegated_by_id FROM grants
         WHERE principal_id = '$bob_id' AND resource_id = 'kettle'")"

# Half a delegator would be read as a DIRECT grant — strictly more access than
# was intended, and invisible.
if psql -X -q -v ON_ERROR_STOP=1 -c \
  "INSERT INTO grants
     (principal_kind, principal_id, resource_kind, resource_id, role,
      granted_at, delegated_by_id)
   VALUES ('user','$bob_id','device','half','admin',now(),'$alice_id')" >/dev/null 2>&1
then bad "half a delegator is refused"
else ok "half a delegator is refused"
fi

# ── The audit table ─────────────────────────────────────────────────────────

audit="$product/migrations/0002_audit.sql"
[ -f "$audit" ] || { echo "no audit migration generated"; exit 1; }

psql_ -f "$audit"
ok "the generated audit migration applies"

expect "every reason the rule can return is storable" \
  "9" "$(psql -X -At -q \
    -c "INSERT INTO grants_audit
          (decided_at, principal_kind, principal_id, action,
           resource_kind, resource_id, allowed, reason)
        SELECT now(), 'user', '$alice_id', 'read', 'device', 'd', false, r
          FROM unnest(ARRAY['granted','device_reading_itself','not_identified',
                            'no_grant','role_too_weak','expired','no_clock',
                            'delegator_lacks_authority','delegation_too_deep']) AS r" \
    -c "SELECT count(*) FROM grants_audit")"

if psql -X -q -v ON_ERROR_STOP=1 -c \
  "INSERT INTO grants_audit
     (decided_at, principal_kind, principal_id, action,
      resource_kind, resource_id, allowed, reason)
   VALUES (now(),'user','$alice_id','read','device','d',false,'vibes')" >/dev/null 2>&1
then bad "a reason the rule cannot return is refused"
else ok "a reason the rule cannot return is refused"
fi

# `allowed` is BOOLEAN here and INTEGER on SQLite. The store reads both as the
# same thing, and this is the half of that claim a real server can check.
expect "allowed is a real boolean on postgres" \
  "boolean" "$(psql -X -At -q -c \
    "SELECT data_type FROM information_schema.columns
      WHERE table_name = 'grants_audit' AND column_name = 'allowed'")"

expect "the audit id is generated rather than supplied" \
  "t" "$(psql -X -At -q \
    -c "INSERT INTO grants_audit
          (decided_at, principal_kind, principal_id, action,
           resource_kind, resource_id, allowed, reason)
        VALUES (now(),'user','$bob_id','write','device','d',true,'granted')" \
    -c "SELECT count(*) > 0 FROM grants_audit WHERE principal_id = '$bob_id' AND id IS NOT NULL")"

echo
if [ "$fail" -eq 0 ]; then
  echo "postgres: everything verified"
else
  echo "postgres: FAILURES above"
  exit 1
fi
