//! Prose freshness — documentation as a gated artifact.
//!
//! # The hole this closes
//!
//! This repository gates generated things well. `fid derive --check` catches a
//! stale artifact, `fid context --check` catches a stale generated block, the
//! captures test catches terminal output the binary no longer prints, and the
//! conformance vectors catch two implementations drifting apart.
//!
//! None of them catch a **sentence**. `AGENTS.md` said *"every contract
//! currently implements only `none`"* for six vendors after it stopped being
//! true, in a repository whose entire argument is that a hand-copied fact
//! drifts. Every gate was green the whole time, because prose is not generated
//! and nothing was watching it.
//!
//! The obvious answer — generate the prose too — does not work, and pretending
//! otherwise is how documentation systems die. A paragraph explaining *why* a
//! contract is shaped a certain way cannot be derived from the contract: if it
//! could, it would carry no information the code does not already carry. The
//! judgment is the point.
//!
//! # What is derived instead
//!
//! Not the prose. **The obligation to revisit it.**
//!
//! A prose block declares what it describes. This module records a hash of
//! that source. When the source changes and the prose was not revisited, the
//! gate fails and names both — the paragraph, and the thing underneath it that
//! moved. A person or an agent re-reads the paragraph, fixes it or decides it
//! is still correct, and accepts it.
//!
//! That is the honest version of "documentation is never out of sync": the
//! text stays hand-written, and going stale stops being silent.
//!
//! ```markdown
//! <!-- fid:describes crates/fiducial-cli/src/adapter.rs#CONTRACTS -->
//! Adapters name contracts, not vendors…
//! <!-- fid:end-describes -->
//! ```
//!
//! # Why a symbol and not just a file
//!
//! A whole-file hash fires on every unrelated edit, and a gate that cries wolf
//! is worse than no gate — it trains the reader to accept without reading,
//! which is exactly the failure it was added to prevent. `#CONTRACTS` narrows
//! the watch to one balanced block, so the paragraph about the contract
//! registry is not woken by a typo fix elsewhere in the same file.

use std::collections::BTreeMap;
use std::path::Path;

use anyhow::{bail, Context, Result};
use serde::{Deserialize, Serialize};

use crate::lock::sha256_hex;

/// The file recording what each prose block was last checked against.
pub const PROSE_LOCK: &str = "docs/prose.lock";

const OPEN: &str = "<!-- fid:describes ";
const CLOSE: &str = "<!-- fid:end-describes -->";

/// One prose block, and the source it claims to describe.
#[derive(Debug, Clone)]
pub struct Block {
    /// Document the block lives in, relative to the root.
    pub document: String,
    /// What it describes: `path` or `path#symbol`.
    pub target: String,
    /// 1-indexed line of the opening marker, for the error message.
    pub line: usize,
}

impl Block {
    /// The lock key. Document plus target, because one document may describe
    /// several sources and one source may be described by several documents.
    pub fn key(&self) -> String {
        format!("{}::{}", self.document, self.target)
    }
}

/// What the lock file holds.
#[derive(Debug, Default, Deserialize, Serialize)]
pub struct ProseLock {
    /// Lock key → hash of the described source when it was last accepted.
    #[serde(default)]
    pub accepted: BTreeMap<String, String>,
}

impl ProseLock {
    pub fn load(root: &Path) -> Result<Self> {
        let path = root.join(PROSE_LOCK);
        let Ok(text) = std::fs::read_to_string(&path) else {
            return Ok(Self::default());
        };
        toml::from_str(&text).with_context(|| format!("parsing {PROSE_LOCK}"))
    }

    pub fn save(&self, root: &Path) -> Result<()> {
        let path = root.join(PROSE_LOCK);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).ok();
        }
        let body = format!(
            "# Generated by `fid docs --accept`. Do not edit by hand.\n\
             #\n\
             # Each entry is a prose block and a hash of the source it describes, as\n\
             # that source stood when someone last read the prose against it. When the\n\
             # source moves on without the prose, `fid docs --check` fails and names\n\
             # both. See crates/fiducial-cli/src/prose.rs for why the prose itself is\n\
             # not generated.\n\n{}",
            toml::to_string_pretty(self).context("serializing the prose lock")?
        );
        std::fs::write(&path, body).with_context(|| format!("writing {PROSE_LOCK}"))
    }
}

/// Every prose block declared in `text`.
pub fn blocks_in(document: &str, text: &str) -> Result<Vec<Block>> {
    let mut out = Vec::new();
    let mut depth = 0usize;
    let mut fence: Option<String> = None;

    for (i, line) in text.lines().enumerate() {
        let trimmed = line.trim();

        // A fenced code block showing the syntax is documentation ABOUT a
        // marker, not a marker. Without this, the example in `AGENTS.md`
        // explaining how to write one registered as a real block describing
        // `adapter.rs` — so the file teaching the mechanism was permanently
        // stale against it.
        //
        // Tracked by fence token so a ``` inside a ~~~ block, or a longer
        // fence nested in a shorter one, does not close the wrong thing.
        if let Some(token) = trimmed
            .strip_prefix("```")
            .map(|_| "```")
            .or_else(|| trimmed.strip_prefix("~~~").map(|_| "~~~"))
        {
            match &fence {
                Some(open) if open == token => fence = None,
                Some(_) => {}
                None => fence = Some(token.to_string()),
            }
            continue;
        }
        if fence.is_some() {
            continue;
        }

        if let Some(rest) = trimmed.strip_prefix(OPEN) {
            if depth > 0 {
                bail!(
                    "{document}:{}: `fid:describes` opened inside another one — \
                     nest them and neither block has a clear boundary",
                    i + 1
                );
            }
            let target = rest
                .strip_suffix("-->")
                .map(str::trim)
                .filter(|t| !t.is_empty())
                .ok_or_else(|| {
                    anyhow::anyhow!(
                        "{document}:{}: `fid:describes` names nothing — \
                         expected `<!-- fid:describes path[#symbol] -->`",
                        i + 1
                    )
                })?;
            out.push(Block {
                document: document.to_string(),
                target: target.to_string(),
                line: i + 1,
            });
            depth += 1;
        } else if trimmed == CLOSE {
            if depth == 0 {
                bail!(
                    "{document}:{}: `{CLOSE}` with no `fid:describes` open",
                    i + 1
                );
            }
            depth -= 1;
        }
    }

    if depth > 0 {
        let open = out.last().expect("depth > 0 implies a block");
        bail!(
            "{document}:{}: `fid:describes {}` is never closed with `{CLOSE}`",
            open.line,
            open.target
        );
    }
    Ok(out)
}

/// The current hash of whatever a target names.
///
/// Returns the error a reader can act on: a target pointing at a file that was
/// deleted, or a symbol that was renamed, is itself a form of staleness and the
/// most useful thing the gate can say.
pub fn hash_target(root: &Path, target: &str) -> Result<String> {
    let (rel, symbol) = match target.split_once('#') {
        Some((p, s)) => (p, Some(s)),
        None => (target, None),
    };

    let path = root.join(rel);
    let text = std::fs::read_to_string(&path)
        .with_context(|| format!("`{target}` describes {rel}, which cannot be read"))?;

    let Some(symbol) = symbol else {
        return Ok(sha256_hex(text.as_bytes()));
    };

    let region = extract(&text, symbol).ok_or_else(|| {
        anyhow::anyhow!(
            "`{target}`: {rel} has no `{symbol}`.\n  \
             It was renamed or removed — which is exactly the kind of change \
             the prose describing it needs to be re-read for."
        )
    })?;
    Ok(sha256_hex(region.as_bytes()))
}

/// The balanced block beginning at the first line containing `symbol`.
///
/// Deliberately not a parser. It matches `{}`, `[]` and `()` and stops when
/// they close, which covers a Rust `static`/`struct`/`fn`, a TypeScript object
/// or interface, and a TOML array — every shape this repository points prose
/// at. A language-aware version would be better and is not worth a syntax tree
/// per language for a staleness heuristic.
///
/// A symbol whose line opens nothing balanced (a `const NAME: &str = "…";`)
/// yields that single line, which is the right answer for it.
fn extract(text: &str, symbol: &str) -> Option<String> {
    let lines: Vec<&str> = text.lines().collect();
    let start = lines.iter().position(|l| l.contains(symbol))?;

    let mut depth = 0i32;
    let mut in_string = false;
    let mut escaped = false;
    let mut end = start;

    for (offset, line) in lines[start..].iter().enumerate() {
        for c in line.chars() {
            if escaped {
                escaped = false;
                continue;
            }
            match c {
                '\\' if in_string => escaped = true,
                '"' => in_string = !in_string,
                '{' | '[' | '(' if !in_string => depth += 1,
                '}' | ']' | ')' if !in_string => depth -= 1,
                _ => {}
            }
        }
        end = start + offset;
        // Depth returns to zero at the end of the first line for a one-liner,
        // and at the closing brace for a block.
        if depth <= 0 {
            break;
        }
    }

    Some(lines[start..=end].join("\n"))
}

/// A block whose source moved since the prose was last read against it.
pub struct Stale {
    pub block: Block,
    /// What went wrong: a changed hash, or a target that no longer resolves.
    pub reason: String,
}

/// The result of checking every block in every document.
pub struct Report {
    /// Blocks needing a re-read, with why.
    pub stale: Vec<Stale>,
    /// Lock key → current hash, for every block whose target resolved.
    pub current: BTreeMap<String, String>,
    /// Every block found, including ones whose target no longer resolves.
    ///
    /// Counted separately from `current` because a target that does not
    /// resolve produces no hash. Deriving the total from `current` made a
    /// document whose only block named a renamed symbol report "no prose
    /// blocks declared" and exit zero — the gate silently disabling itself in
    /// precisely the case it was built to catch.
    pub total: usize,
}

/// Check every block in every document, returning what is stale.
pub fn check(root: &Path, documents: &[String]) -> Result<Report> {
    let lock = ProseLock::load(root)?;
    let mut stale = Vec::new();
    let mut current = BTreeMap::new();
    let mut total = 0usize;

    for document in documents {
        let Ok(text) = std::fs::read_to_string(root.join(document)) else {
            continue;
        };
        if !text.contains(OPEN) {
            continue;
        }
        for block in blocks_in(document, &text)? {
            total += 1;
            let key = block.key();
            match hash_target(root, &block.target) {
                Ok(hash) => {
                    current.insert(key.clone(), hash.clone());
                    match lock.accepted.get(&key) {
                        Some(accepted) if *accepted == hash => {}
                        Some(_) => stale.push(Stale {
                            block,
                            reason: "the source changed since this was last read".to_string(),
                        }),
                        None => stale.push(Stale {
                            block,
                            reason: "never accepted — no record of anyone reading this \
                                     against its source"
                                .to_string(),
                        }),
                    }
                }
                Err(e) => stale.push(Stale {
                    block,
                    reason: format!("{e:#}"),
                }),
            }
        }
    }

    Ok(Report {
        stale,
        current,
        total,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_block_records_its_document_and_target() {
        let text =
            "intro\n<!-- fid:describes src/a.rs#FOO -->\nprose\n<!-- fid:end-describes -->\n";
        let blocks = blocks_in("README.md", text).unwrap();
        assert_eq!(blocks.len(), 1);
        assert_eq!(blocks[0].target, "src/a.rs#FOO");
        assert_eq!(blocks[0].key(), "README.md::src/a.rs#FOO");
        assert_eq!(blocks[0].line, 2);
    }

    #[test]
    fn an_unclosed_block_names_the_marker_that_opened_it() {
        let err = blocks_in("A.md", "<!-- fid:describes src/a.rs -->\nprose\n").unwrap_err();
        let msg = format!("{err:#}");
        assert!(msg.contains("never closed"), "{msg}");
        assert!(msg.contains("src/a.rs"), "{msg}");
    }

    #[test]
    fn a_close_without_an_open_is_an_error() {
        let err = blocks_in("A.md", "<!-- fid:end-describes -->\n").unwrap_err();
        assert!(format!("{err:#}").contains("no `fid:describes` open"));
    }

    #[test]
    fn a_marker_naming_nothing_is_rejected() {
        let err = blocks_in(
            "A.md",
            "<!-- fid:describes -->\nx\n<!-- fid:end-describes -->\n",
        )
        .unwrap_err();
        assert!(format!("{err:#}").contains("names nothing"));
    }

    #[test]
    fn a_symbol_selects_its_balanced_block_and_nothing_after_it() {
        let src = "before\nstatic CONTRACTS: &[C] = &[\n  C { name: \"a\" },\n];\nafter\n";
        let got = extract(src, "CONTRACTS").unwrap();
        assert!(got.starts_with("static CONTRACTS"), "{got}");
        assert!(got.ends_with("];"), "{got}");
        assert!(!got.contains("after"), "{got}");
        assert!(!got.contains("before"), "{got}");
    }

    #[test]
    fn a_brace_inside_a_string_does_not_open_a_block() {
        // `"{"` used to open a block that never closed, swallowing the file
        // and making the hash depend on everything below it.
        let src = "static X: &str = \"{\";\nunrelated\n";
        let got = extract(src, "static X").unwrap();
        assert_eq!(got, "static X: &str = \"{\";");
    }

    #[test]
    fn a_one_line_symbol_yields_that_line() {
        let got = extract("const A: u8 = 1;\nconst B: u8 = 2;\n", "const A").unwrap();
        assert_eq!(got, "const A: u8 = 1;");
    }

    #[test]
    fn a_marker_inside_a_code_fence_is_an_example_not_a_block() {
        // The file that documents the syntax must not be watched by it.
        let text = "How to write one:\n\n\
                    ```markdown\n\
                    <!-- fid:describes src/a.rs -->\n\
                    prose\n\
                    <!-- fid:end-describes -->\n\
                    ```\n\n\
                    done\n";
        assert!(blocks_in("AGENTS.md", text).unwrap().is_empty());
    }

    #[test]
    fn a_real_block_after_a_fenced_example_is_still_found() {
        let text = "```\n<!-- fid:describes src/x.rs -->\n```\n\
                    <!-- fid:describes src/real.rs -->\nprose\n\
                    <!-- fid:end-describes -->\n";
        let blocks = blocks_in("A.md", text).unwrap();
        assert_eq!(blocks.len(), 1);
        assert_eq!(blocks[0].target, "src/real.rs");
    }

    #[test]
    fn a_missing_symbol_is_reported_rather_than_hashing_the_file() {
        assert!(extract("nothing here\n", "CONTRACTS").is_none());
    }
}
