/**
 * @fiducial/adapters — cross-platform adapter contracts.
 *
 * Each contract is a TypeScript interface + a `None*` no-op class. The same
 * contracts exist as Rust traits in `crates/fiducial-adapters`. Both sides are
 * kept in sync by design; `fid derive` generates factory wiring from the
 * `[adapters]` declaration in `fiducial.toml`.
 *
 * Import the sub-path for tree-shaking:
 *   import { NoneDatabase } from "@fiducial/adapters/database";
 *
 * Or import everything here for convenience:
 *   import { NoneDatabase, NoneStorage, NoneEmail, NoneDiagnostics } from "@fiducial/adapters";
 */

export type { Database, Row, SqlValue, WriteResult } from "./database.js";
export { D1Database, DatabaseError, MapRow, NoneDatabase } from "./database.js";

export type { Storage } from "./storage.js";
export { NoneStorage, R2Storage, StorageError } from "./storage.js";

export type { Email, Message } from "./email.js";
export { EmailError, NoneEmail } from "./email.js";

export type { Diagnostics, DiagnosticsLevel } from "./diagnostics.js";
export { NoneDiagnostics } from "./diagnostics.js";

import type { Database } from "./database.js";
import type { Storage } from "./storage.js";
import type { Email } from "./email.js";
import type { Diagnostics } from "./diagnostics.js";
import { NoneDatabase } from "./database.js";
import { NoneStorage } from "./storage.js";
import { NoneEmail } from "./email.js";
import { NoneDiagnostics } from "./diagnostics.js";

/**
 * The full adapter set — one of these per product, built from `[adapters]`
 * in `fiducial.toml`.
 *
 * The concrete factory (`createAdapters`) is generated by `fid derive` into
 * `src/adapters.generated.ts`. Import from there in application code:
 *
 * ```ts
 * import { createAdapters } from "./adapters.generated.js";
 * const adapters = createAdapters(env);
 * ```
 */
export interface AdapterSet {
  database: Database;
  storage: Storage;
  email: Email;
  diagnostics: Diagnostics;
}

/**
 * Build an adapter set where every contract is a no-op.
 *
 * Useful in tests, storybook, and any context where real vendor calls are not
 * wanted. The generated `createAdapters(env)` from `fid derive` calls the
 * right vendor constructors instead.
 */
export function createNoneAdapters(): AdapterSet {
  return {
    database: new NoneDatabase(),
    storage: new NoneStorage(),
    email: new NoneEmail(),
    diagnostics: new NoneDiagnostics(),
  };
}
