/**
 * @fiducial/adapters — cross-platform adapter contracts.
 *
 * Each contract is a TypeScript interface + a `None*` no-op class. The same
 * contracts exist as Rust traits in `crates/fiducial-adapters`. Both sides are
 * kept in sync by design; `fid derive` generates factory wiring from the
 * `[adapters]` declaration in `fiducial.toml`.
 *
 * Import the sub-path for tree-shaking:
 *   import { NoneDatabase } from "@fiducial/adapters/database";
 *
 * Or import everything here for convenience:
 *   import { NoneDatabase, NoneStorage, NoneEmail, NoneDiagnostics } from "@fiducial/adapters";
 */

export type { Database, Row, SqlValue, WriteResult } from "./database.js";
export { D1Database, DatabaseError, MapRow, NoneDatabase } from "./database.js";

export type { Storage } from "./storage.js";
export { NoneStorage, R2Storage, StorageError } from "./storage.js";

export type { Email, Message } from "./email.js";
export { EmailError, NoneEmail } from "./email.js";

export type { Diagnostics, DiagnosticsLevel } from "./diagnostics.js";
export { NoneDiagnostics } from "./diagnostics.js";

export type { BotProtection, VerifyOutcome } from "./bot-protection.js";
export {
  BotProtectionError,
  NoneBotProtection,
  Turnstile,
} from "./bot-protection.js";

export type { Queue } from "./queue.js";
export { CloudflareQueue, NoneQueue, QueueError } from "./queue.js";

// `Auth` is not part of `AdapterSet` — see its own doc comment in auth.ts for
// why: every other contract here is env-scoped, and a real Auth
// implementation is request-scoped (it needs a session store bound to the
// current request's cookies or Authorization header). `createAuth(env, store)`
// is a separate factory `fid derive` generates alongside `createAdapters(env)`.
export type {
  Auth,
  AuthKeyValueStore,
  AuthSession,
  AuthSessionContext,
  AuthUser,
} from "./auth.js";
export {
  AuthError,
  BearerSessionContext,
  CookieKeyValueStore,
  CookieSessionContext,
  MemoryKeyValueStore,
  NoneAuth,
  SupabaseAuth,
} from "./auth.js";

import type { Database } from "./database.js";
import type { Storage } from "./storage.js";
import type { Email } from "./email.js";
import type { Diagnostics } from "./diagnostics.js";
import type { BotProtection } from "./bot-protection.js";
import type { Queue } from "./queue.js";
import { NoneDatabase } from "./database.js";
import { NoneStorage } from "./storage.js";
import { NoneEmail } from "./email.js";
import { NoneDiagnostics } from "./diagnostics.js";
import { NoneBotProtection } from "./bot-protection.js";
import { NoneQueue } from "./queue.js";

/**
 * The full adapter set — one of these per product, built from `[adapters]`
 * in `fiducial.toml`.
 *
 * The concrete factory (`createAdapters`) is generated by `fid derive` into
 * `src/adapters.generated.ts`. Import from there in application code:
 *
 * ```ts
 * import { createAdapters } from "./adapters.generated.js";
 * const adapters = createAdapters(env);
 * ```
 */
export interface AdapterSet {
  database: Database;
  storage: Storage;
  email: Email;
  diagnostics: Diagnostics;
  botProtection: BotProtection;
  queue: Queue;
}

/**
 * Build an adapter set where every contract is a no-op.
 *
 * Useful in tests, storybook, and any context where real vendor calls are not
 * wanted. The generated `createAdapters(env)` from `fid derive` calls the
 * right vendor constructors instead.
 */
export function createNoneAdapters(): AdapterSet {
  return {
    database: new NoneDatabase(),
    storage: new NoneStorage(),
    email: new NoneEmail(),
    diagnostics: new NoneDiagnostics(),
    botProtection: new NoneBotProtection(),
    queue: new NoneQueue(),
  };
}
