//! Extract the platform's principles from `MISSION.md` at build time.
//!
//! The principles are declared in exactly one place: `MISSION.md`. A scaffolded
//! product cannot link to that file — its own `MISSION.md` states what the
//! *product* is for — so it needs the text. Copying it into the template would
//! be a second declaration, which is the thing principle 1 forbids.
//!
//! So the template carries a `{{principles}}` placeholder and this script fills
//! it from the source of truth. Editing `MISSION.md` changes what every future
//! product inherits, with no second file to remember.
//!
//! An earlier attempt kept a hand-written copy in the template and added a test
//! asserting the two agreed. That caught drift but did not prevent it — a gated
//! duplicate is still a duplicate.
//!
//! # Built-in capabilities
//!
//! The same argument, applied a second time. Every built-in capability used to
//! be a `CapabilityDef` literal listing its files by hand — 56 `include_str!`
//! calls next to a directory that already contained exactly those files. Adding
//! a file to a capability meant editing two places, and forgetting the second
//! shipped a capability missing a file with nothing to catch it.
//!
//! So the **directory is the declaration** and the embedded registry is derived
//! from it. A file added to `capabilities/<id>/` is installed by `fid add <id>`
//! with no Rust to edit, and a capability resolved from a git repository at
//! runtime goes through the identical derivation — which is the property that
//! makes "a capability need not be compiled into the CLI" true rather than
//! aspirational.

use std::path::Path;

fn main() {
    principles();
    capabilities();
}

/// Embed every `capabilities/<id>/` directory as `(path, content)` pairs.
///
/// Deliberately *not* a parsed manifest: this emits bytes, and
/// `capability::manifest::derive` turns bytes into a capability at runtime —
/// the same function, on the same shape of input, as a third-party capability
/// read from disk. A build script that produced the parsed form would be a
/// second implementation of the derivation, in a place no test can reach.
fn capabilities() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let root = Path::new(&manifest_dir).join("capabilities");
    println!("cargo:rerun-if-changed={}", root.display());

    let mut ids: Vec<String> = std::fs::read_dir(&root)
        .unwrap_or_else(|e| panic!("reading {}: {e}", root.display()))
        .filter_map(|e| e.ok())
        .filter(|e| e.path().is_dir())
        .map(|e| e.file_name().to_string_lossy().to_string())
        .collect();
    ids.sort();

    let mut out = String::new();
    out.push_str("// GENERATED by build.rs from crates/fiducial-cli/capabilities/.\n");
    out.push_str("// The directory is the declaration; this is the derivation.\n\n");
    out.push_str("pub static BUILTIN_FILES: &[(&str, &[(&str, &str)])] = &[\n");

    for id in &ids {
        let dir = root.join(id);
        let mut files = Vec::new();
        collect(&dir, &dir, &mut files);
        files.sort();

        out.push_str(&format!("    ({id:?}, &[\n"));
        for rel in files {
            // `include_str!` rather than the bytes inline: the file stays the
            // thing cargo tracks, so editing it rebuilds.
            let abs = dir.join(&rel);
            println!("cargo:rerun-if-changed={}", abs.display());
            out.push_str(&format!(
                "        ({rel:?}, include_str!({:?})),\n",
                abs.to_string_lossy()
            ));
        }
        out.push_str("    ]),\n");
    }
    out.push_str("];\n");

    let dest = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR")).join("capabilities.rs");
    std::fs::write(&dest, out).expect("writing capabilities.rs");
}

fn collect(root: &Path, dir: &Path, out: &mut Vec<String>) {
    for entry in std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("reading {}: {e}", dir.display()))
        .flatten()
    {
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().to_string();
        if name.starts_with('.') && name != ".cargo" {
            continue;
        }
        if path.is_dir() {
            collect(root, &path, out);
        } else {
            out.push(
                path.strip_prefix(root)
                    .expect("walked below root")
                    .to_string_lossy()
                    .replace('\\', "/"),
            );
        }
    }
}

fn principles() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let manifest = Path::new(&manifest);

    // Two candidates, and the order matters.
    //
    // `MISSION.md` beside this manifest is a **symlink** to the workspace root
    // copy — one file, not two. It exists because `cargo package` cannot reach
    // outside a package's own directory, so a published `fiducial-cli` tarball
    // contained no MISSION.md and its build script panicked reading one two
    // levels up:
    //
    //   reading /…/target/MISSION.md: No such file or directory
    //
    // That made `fiducial-cli` unpublishable, and nothing said so until
    // `cargo publish --dry-run` ran for the first time on 2026-09-16.
    //
    // The workspace-root fallback is for a checkout where the symlink did not
    // survive — git on Windows without symlink support writes a small text file
    // holding the link target instead. That file parses as Markdown with no
    // principles in it, so the fallback is keyed on *finding principles*, not
    // on the file existing: a wrong answer here silently ships a product
    // scaffold with an empty principles block.
    let candidates = [
        manifest.join("MISSION.md"),
        manifest
            .ancestors()
            .nth(2)
            .expect("fiducial-cli sits two levels below the workspace root")
            .join("MISSION.md"),
    ];

    for path in &candidates {
        println!("cargo:rerun-if-changed={}", path.display());
    }

    let principles = candidates
        .iter()
        .find_map(|path| {
            let text = std::fs::read_to_string(path).ok()?;
            extract_principles(&text)
        })
        .unwrap_or_else(|| {
            panic!(
                "no principles section found in any of: {}",
                candidates
                    .iter()
                    .map(|p| p.display().to_string())
                    .collect::<Vec<_>>()
                    .join(", ")
            )
        });

    let out = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR")).join("principles.md");
    std::fs::write(&out, principles).expect("writing principles.md");
}

/// The body between the principles heading and the next top-level heading.
///
/// Matched on the `· ` marker each principle carries rather than on the heading
/// text, so renaming the section — "Seven principles" stopped being accurate the
/// moment 1b, 1c, 5b and 5c were added — does not silently produce an empty
/// block.
fn extract_principles(text: &str) -> Option<String> {
    let mut lines = text.lines().enumerate();

    let start = lines.find_map(|(index, line)| {
        let lower = line.to_ascii_lowercase();
        (line.starts_with("## ") && lower.contains("principle")).then_some(index)
    })?;

    let body: Vec<&str> = text.lines().skip(start + 1).collect();
    let end = body
        .iter()
        .position(|line| line.starts_with("## "))
        .unwrap_or(body.len());

    let section = body[..end].join("\n");
    let section = section.trim_matches(|c: char| c == '\n' || c == '-' || c.is_whitespace());

    // A section that carries no principle markers means the format moved.
    if !section.contains(" · ") {
        return None;
    }
    Some(section.to_string())
}
